Finish mobile version
frnega/Portfolio-setup-and-mobile-firs pull request #3
Opened 2022-08-24 13:40 UTC by frnega

2022-08-24 17:55 UTC, isaacpitwa requested changes
Hi @frnega  🙂 ,

You have done a tremendous job setting up your project. I really like it :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Alt Text](https://media.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-large.gif)


## Highlights 
- All linters are passing  ✅
- Correct use of GitHub flow ✅
- Well documented Repository ✅
-  Clean and readable code base ✅

## Required changes ♻️ 

- [ ] Please add a description to your Pull Request. As your PR will be invalidated  with missing Pull Request Description .

Check the comments under the review.

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Check the comments under the review.





Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @isaacpitwa.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 17:55 UTC, isaacpitwa commented on index.html
> +
- [ ] it would be easier to style with all work cards wrapped into one container which is the `section` work and the work cards represented as cards using `div`. A structure like one below  
``` 
<section class="work-section">
   <h3>MY RECENT WORK</h3>
    <div class="work-card">...</div>
     <div class="work-card">...</div>
      <div class="work-card">...</div>
</section>
```

2022-08-25 11:52 UTC, frnega commented
changed the changes requested

2022-08-25 12:51 UTC, Abenezer-Tilahun requested changes
Hi @frnega  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights

✔️ No linter errors.
✔️ You used correct Github Flow.
✔️ Professional README 

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

- [ ] Pull Request should have a descriptive title telling you what changes are inside and should have a short summary describing introduced changes in more detail. Your Pull Request is still empty ,so try to update your Pull Request as suggested by the previous reviewer.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 12:51 UTC, Abenezer-Tilahun commented on index.html
> +			</div>
- [ ] Kindly,  use `ul` tag for grouping a list  project technologies (e.g., "CSS", "HTML" and "bootstrap") and each of them with a `li` tag to list out.

2022-08-25 12:51 UTC, Abenezer-Tilahun commented on index.html
> +		</div>
- [ ] Kindly,  use `ul` tag for grouping a list  project technologies (e.g., "CSS", "HTML" and "bootstrap") and each of them with a `li` tag to list out.

2022-08-25 12:51 UTC, Abenezer-Tilahun commented on index.html
> +		</div>
- [ ] Kindly,  use `ul` tag for grouping a list  project technologies (e.g., "CSS", "HTML" and "bootstrap") and each of them with a `li` tag to list out.

2022-08-25 12:51 UTC, Abenezer-Tilahun commented on index.html
> +		</div>
- [ ] Kindly,  use `ul` tag for grouping a list  project technologies (e.g., "CSS", "HTML" and "bootstrap") and each of them with a `li` tag to list out.

2022-08-25 12:51 UTC, Abenezer-Tilahun commented on index.html
> +<br>
- [ ] Please try to implement the the button styling: Active, Hover and Pressed (Just like Figma design) show below.
![1](https://user-images.githubusercontent.com/93598189/186664061-518b752a-7819-4f53-8c86-d40c82af43fa.PNG)

2022-08-25 12:51 UTC, Abenezer-Tilahun commented on style.css
> +}
- [ ] Great work on designing styling and addressing the previous reviewer suggestion.
- [ ] Please try to  align the elements according to the requirement, you should use Flex-box in all 2 sections(work and about section.) For Minimum mobile screen size at  375px, it's not aligned left according to requirement(checkout below image of your project)
- Both work and about section must have the margins (top, bottom, left, right) defined in the Template design.

Your Project Look likes this : 
![12](https://user-images.githubusercontent.com/93598189/186668075-928ccf23-9c75-4a75-b742-18e55d0dda50.PNG)

The Figma design Look like : (It's aligned on both side)

![123](https://user-images.githubusercontent.com/93598189/186668294-7cbdcc65-0522-4540-b90a-e997c018a358.PNG)

2022-08-25 13:29 UTC, frnega commented
in this pull request use  changed the div tag to ul tag for grouping a list project technologies (e.g., "CSS", "HTML" and "bootstrap") and changed each of the list with a li tag to list out also tried to implement the  button styling and  also tried to align the elements according to the requirement

2022-08-25 13:41 UTC, Nemwel-Boniface approved these changes
## Hello @frnega               :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for making the requested changes good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-25 13:53 UTC, merged