change to portfolio page to desktop version
frnega/Portfolio-setup-and-mobile-firs pull request #7
Opened 2022-09-01 17:18 UTC by frnega

in this project

- tried to implement media query
- try to work on template 4 as much as i can
- used flexbox

2022-09-01 17:39 UTC, vickymarz requested changes
Hi @frnega , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project, that does not follow GitHub flow. You will need to create a pull request to compare your `feature `branch with the` main` branch and submit the link to that pull request via your Dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-09-01 18:58 UTC, levy002 requested changes
## Hello @frnega   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._   

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [OPTIONAL] Kindly make sure to write your commit message in imperative tense and capitalized it. Please check this [lesson](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to understand it clearly.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-01 18:58 UTC, levy002 commented on style.css
> +}
- [ ] Kindly make sure to set your desktop version breakpoint correctly. If we use the breakpoint of `max-width: 760px` actually we are saying that only all the screens with the maximum width of `760px` must adapt the style we have written inside that block. I highly recommend you to use `min-width` and as requested in the requirement the width value must be between `768x` and `1440px`.  
 For example, we say `@media only screen and (min-width: 768px){}` this means our style inside this will only adapt on all screens with minimum width of `768px`. Please go ahead and correct your screen version breakpoint :wink: 
    ### For more information please checkout this [lesson.](https://www.browserstack.com/guide/what-are-css-and-media-query-breakpoints#:~:text=Essentially%2C%20media%20query%20breakpoints%20are,offers%20an%20optimal%20user%20experience.)

- [ ] Kindly make sure to stick to the provided Figma design. Please check the screenshots below of how your app is looking now on different screens and make sure to make it look exactly like the provided [Figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A10). :wink: 
   - ### Your design (width: 375px)
   ![mobile (1)](https://user-images.githubusercontent.com/87197412/187988943-10d648c0-700d-4f13-81cf-2a2903b0842e.png)

   

 

  - ### Your design (width: 1280px)
   ![mobile (2)](https://user-images.githubusercontent.com/87197412/187989324-ed604fbc-cc7f-4ba6-8113-f15f7d4bdcb6.png)

2022-09-02 07:00 UTC, frnega commented
In this project tried to adapt to my version of desktop portfolio and changed the media section and tried to make it look like the one in figma design

2022-09-02 07:11 UTC, mgmediaweb requested changes
Hi @frnega, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost2](https://user-images.githubusercontent.com/41912912/188079327-c4675f47-ef85-4f3c-8867-5033dfa429b7.gif)

 ## Highlights 💯 
- I appreciate your effort, you can do it! ✔️ 

 ## Required Changes ♻️

*** Kindly, I suggest you follow the advice of the previous reviewer, your site is currently a bit far from the original Figma design, I suggest you do a general review of your site and compare it with the proposal and make the necessary adjustments.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 07:17 UTC, frnega commented
@mgmediaweb can you please specify the changes must look like since am not able to understand your  feedback

2022-09-02 08:36 UTC, merged

2022-09-02 08:37 UTC, BertrandConxy requested changes
Hi @frnega , 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions
- good PR


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-02 08:37 UTC, BertrandConxy commented on style.css
> +@media only screen and (min-width: 760px) {
- [ ] Good job so far 👏. I appreciate your effort in implementing the changes requested. However, **It looks like you have not changed the min-width to a value higher than you have set**. Actually, from the project requirements, **the min-width for the desktop screens should be between 768px and 1440px** 😎. PLease adjust on that 🙏

2022-09-02 08:37 UTC, BertrandConxy commented on index.html
> +				<i class="fa fa-fw fa-envelope"></i>
- [ ] [OPTIONAL] Please make your navigation items links. As you can see, you forgot to add the `href`  attribute to your links. As a consequence, they are not clickable. Please correct on that 😉

2022-09-02 08:37 UTC, BertrandConxy commented on style.css
>    background-size: contain;
- [ ] [OPTIONAL] Please adjust your desktop styles so as to match the Figma design. Look at the comparison below 👇 
**Figma design**
![image](https://user-images.githubusercontent.com/90222110/188098213-50bbbbae-5920-4368-9fb9-80089bd81a08.png)

**Your design**
![image](https://user-images.githubusercontent.com/90222110/188098350-f7412659-21da-42e3-b963-df31bdf72e6a.png)

2022-09-02 08:37 UTC, BertrandConxy commented on style.css
> +#mail {
- [ ] [OPTIONAL] Please adjust your styles to match the Figma design concerning the project cards. Please look at the comparison below 👇 
**Figma design**
![image](https://user-images.githubusercontent.com/90222110/188098896-bd62fb7c-b90c-494a-b94c-ce5388894e48.png)

**Your design**
![image](https://user-images.githubusercontent.com/90222110/188099022-e405f88d-0a00-45c5-9611-84a3613455fd.png)

2022-09-02 08:37 UTC, BertrandConxy commented on style.css
> -  left: 0;
- [ ] [OPTIONAL] It looks like the mobile version of your portfolio is no longer aligning with the Figma design mobile version given. It is among the requirements to keep your mobile version correct 👍

2022-09-02 13:42 UTC, frnega commented on style.css
> -  left: 0;
hey @BertrandConxy  when trying to merge the animation  pull request this one also merged what can i do